
export interface VITPattern {
  subject: string;
  style: string;
  samples: string[];
}

export const VIT_KNOWLEDGE_BASE: VITPattern[] = [
  {
    subject: "Data Structures and Algorithms",
    style: "Focus on asymptotic analysis, worst-case complexity proofs, and step-by-step trace of algorithms like AVL rotations or Dijkstra's. Questions often combine two concepts (e.g., 'Perform Heap Sort and show the state of the max-heap after 3 deletions').",
    samples: [
      "Define Big-Oh notation and prove that 3n^2 + 5n = O(n^2). (2 Marks)",
      "Explain the process of balancing an AVL tree with a 'Left-Right' rotation using a concrete example. (5 Marks)",
      "Develop a recursive algorithm to find the height of a Binary Search Tree and analyze its time complexity. (10 Marks)",
      "Algorithm SUMsubarray(A[], n, Lower, Upper). Find output for specific inputs and time complexity. Propose efficient 'Alternatesum' algorithm.",
      "Convert the scoring rule formula '(A+B)^C+D/(E+F)*G+H/I' to postfix using a stack. Show step-by-step stack status.",
      "School canteen serving rule: Odd positions served first (priority), then even. Write pseudocode and trace for [S1..S6].",
      "Military squad sorting: Soldiers have engagement times. Repeatedly pick fastest remaining and place in order. Illustrate step-by-step.",
      "Nursery sapling arrangement (BST logic): Smaller ID left, Larger ID right. Insert 73, 45, 40, 90... Show in-order walk and search paths.",
      "Disaster response: Shortest path from relief camp A to others using weighted graph. Show tentative distances updates.",
      "Library Hash Table: Insert Book IDs 101, 112... into 15 slots using Quadratic Probing. Count probing attempts.",
      "Circular game: Participants in circular linked list. Pass ball k steps, eliminate node. Write pseudocode for creation, deletion, and simulation.",
      "Mineral processing: Priority values in Complete Binary Tree. Reorder for max-heap? Show rearrangement steps for [15, 70, 60...].",
      "Two algorithms trade-off: O(n^3)/O(1) vs O(n log n)/O(n). Analyze for memory-constrained devices.",
      "Analyze complexity of nested loops: i=1..n, j=n..1 (j/=2), k=1..i. Also Recurrence T(n)=2T(n/2)+4n.",
      "Convert expression 'A/(B^C)+(D+E)-(A*C)' to prefix using stack. Evaluate for A=4, B=2...",
      "Divide and Conquer strategy to find number 21 in sorted array. Count comparisons vs unsorted linear search.",
      "Compute diameter of a binary tree (longest path between leaf nodes). Pseudocode and trace.",
      "Broadcasting in hierarchical network (Binary Tree). Which traversal ensures level-by-level delivery?",
      "BST with Subtree Size: Algorithm to Insert(x), Delete(x), and return k-th largest in O(h).",
      "Campus navigation: Shortest path from Entrance A using Dijkstra. Handle ties lexicographically.",
      "Underground cable network: MST for 7 locations (A..Z) with costs. Minimize total cable length.",
      "Hash Table collisions: Separate chaining vs Linear Probing vs Quadratic Probing vs Double Hashing.",
      "Min-Heap Delivery Queue: [5, 10, 15...]. Simulate deletion of root and reheapification.",
      "Order_Book as AVL Tree: Insert prices [50, 20, 70...]. Show rotations (LL, LR, RR, RL). Delete nodes and rebalance.",
      "Recurrence T(n)=2T(n/2)+4n. Solve using recursion tree. What if branching factor becomes 4?",
      "Queue using Two Stacks: Enqueue on S1, Dequeue from S2. Trace operations. Write pseudocode.",
      "Reverse Singly Linked List: In-place reversal. Iterative vs Recursive pseudocode.",
      "Sort list elements only at indices divisible by k. Remaining elements stay fixed. Complexity analysis.",
      "Transform Binary Tree to Sum Tree. Calculate difference between sum of even and odd levels.",
      "Fiber-optic network MST. Update MST if specific direct connections (A-G, G-H) are mandatory.",
      "Double Hashing truck registration: h1(k) = k mod 11, h2(k) = 6 - (k mod 6). Insert keys 37, 48...",
      "Postfix to Expression Tree: '12 25 + 30 ...'. Construct tree, evaluate, and derive infix.",
      "Warehouse Inventory AVL: Insert/Delete Product IDs. Determine height and list leaf/internal nodes.",
      "Time complexity of loop: i=n/2..n, j=1..n, k=1..n (k*=2). Recurrence T(n)=2T(n-1)+1.",
      "SkyDrop ride: Fixed array queue cap 5. Service only if >=3 waiting. No shifting elements.",
      "Merge Sort on financial transactions. Explain Divide, Conquer, Merge steps and time complexity.",
      "Complete vs Perfect Binary Tree. Algorithm to check Completeness. Expression tree from Postfix.",
      "BST with Duplicates: Store (key, frequency). Decrement freq on delete. Trace insertions/deletions.",
      "Smart Township Power: Prim's algorithm for MST. Complexity dependence on V and E.",
      "Rehashing: Linear probing, load factor > 0.7 triggers resize. Trace insertions [120, 126...].",
      "Circular shift of Linear Linked List by k positions. Pseudocode.",
      "Doubly Linked List swap: Search KEY. If odd, swap with head. If even, swap with tail."
    ]
  },
  {
    subject: "Operating Systems",
    style: "Heavy focus on Process Synchronization (Semaphores, Mutex, Monitors) with custom scenarios (Robots, Painting, Game Servers, Drones, Smart Cities). Deadlock detection (RAG) and avoidance (Banker's Algorithm) are critical. Memory Management involves numericals on Paging, TLB EAT calculations, and Partition Allocation. Real-world system design (Airline, Hospital, Smart TV, Electric Vehicles) is common.",
    samples: [
      "In a smart research facility, multiple robots need access to a 3D printer. Write pseudo code to synchronize the robots using the 'choosing number' approach to ensure mutual exclusion and fairness. (10 Marks)",
      "Design an operating system architecture for an airline reservation system handling millions of schedules. Explain modularity, security, and dependability. (10 Marks)",
      "Using Pthreads, create three threads to calculate the Sum, Maximum, and Average of an array of integers. (10 Marks)",
      "Schedule background services (Antivirus, Disk clean-up, System update) using Priority Scheduling and Round Robin (5ms). Draw Gantt Charts and calculate Avg Turnaround/Waiting Time. (10 Marks)",
      "Analyze Deadlock in a Lab scenario with resources (GPU, Display, Printer, HDD). Draw Resource Allocation Graph and determine if the system is in a Safe State. (10 Marks)",
      "Synchronization for Hospital Operating Rooms: Emergency surgeries have priority over Elective ones. Max 2 surgeries at a time. Write pseudocode using synchronization tools. (10 Marks)",
      "Identify the type of hypervisor suitable for testing cross-platform applications (Windows, Linux) on a single developer machine. Discuss resource allocation. (10 Marks)",
      "File Allocation: Store files (StudentRecords, Attendance, etc.) on a 1GB disk with 10MB blocks. Suggest a method for contiguous allocation handling pre-occupied blocks. (10 Marks)",
      "Page Replacement: Video streaming service with 4 memory frames. Reference string: 0 1 2 3 2 5 6... Compare FIFO, LRU, and Optimal algorithms. (15 Marks)",
      "Disk Scheduling: Streaming movies stored on tracks 0-499. Head at 250. Requests: 23, 389, 120... Calculate movement for SSTF, SCAN, and LOOK. (15 Marks)",
      "Explain protection achieved through abstraction in a microkernel OS using a C code example. (10 Marks)",
      "Write a C program using fork() where Parent computes sum of even numbers and Child creates threads for sum of odd numbers and average. Draw process state diagram. (10 Marks)",
      "SRTF Scheduling: Processes P1-P5 with arrival and burst times. Calculate execution sequence and waiting times. Discuss impact on responsiveness. (10 Marks)",
      "Identify the Race Condition in a Drone Control System (Sensor Thread vs Control Thread). Modify code using synchronization to fix data inconsistency. (10 Marks)",
      "Readers-Writers Problem: Log monitoring system. Prioritize Writers over Readers. Write pseudocode using Semaphores/Monitors. (10 Marks)",
      "File Allocation: Allocate blocks for files (kernel, logs, config) using Contiguous, Linked (FAT), and Indexed methods. Handle file growth. (10 Marks)",
      "Disk Scheduling: Library Robot. Requests: 98, 183, 41... Calculate movement for FCFS, SCAN, and C-SCAN strategies. (10 Marks)",
      "Banker's Algorithm: Cooking Competition (Chefs A, B, C sharing chopping boards, knives, bowls). Determine Safe Sequence and if a request can be granted. (15 Marks)",
      "Memory Allocation: Allocate processes P1-P4 to partitions using Best Fit, Worst Fit, and First Fit. Calculate internal fragmentation. (15 Marks)",
      "Page Replacement: Game Player Substitution scenario. Reference string provided. Compare LRU vs Optimal strategies. (15 Marks)",
      "Design an efficient OS for a Smart TV. Block diagram of hardware components and OS functionalities. (10 Marks)",
      "Process Lifecycle: Describe states and steps for program execution. Write a program for specific termination sequence (Parent last, Child 3 first). (10 Marks)",
      "Bank Help Desk Scheduling: SJF, Priority (Token based), and Round Robin (2ms). Calculate Avg Waiting Time. (10 Marks)",
      "Restaurant Deadlock: Chefs A, B, C sharing resources. Check if allocation is safe. (10 Marks)",
      "Synchronization: P1(S1), P2(S2), P3(S3). Enforce sequence S3 -> S1 -> S2 using Semaphores. (10 Marks)",
      "Lab Allocation: 5 workshops, 6 laboratories with different capacities. Best Fit allocation strategy. (10 Marks)",
      "Segmentation: Map Logical Addresses to Physical Addresses given a Segment Table. (10 Marks)",
      "Page Replacement: LRU vs FIFO for reference string 7, 2, 3, 1... with 3 frames. (10 Marks)",
      "Disk Scheduling: FCFS vs SCAN for 1000 cylinders. Head at 431. (10 Marks)",
      "File Allocation: Perform allocation for given directory structures (Structure 1, 2, 3). (10 Marks)",
      "Design a customized OS for Smart Medical Diagnostic machines. Architecture suggestion and justification. (10 Marks)",
      "Multithreading: Calculate sum of highest digits of two large integers using threads. (10 Marks)",
      "Readers-Writers: Writer Priority. 3rd writer waits for 5 readers. Semaphore solution. (10 Marks)",
      "Page Replacement: Optimal vs Second Chance for reference string 1, 0, 2... (10 Marks)",
      "TLB: Calculate Effective Access Time (EAT). Logical to Physical address translation bits calculation. (10 Marks)",
      "File Allocation: Contiguous vs Indexed. Diagrammatic illustration for specific file sizes and blocks. (10 Marks)",
      "Disk Scheduling: SCAN vs LOOK for 2000 cylinders. Head at 143. (10 Marks)",
      "Virtualization approaches and Security threats for Online Shopping App on custom OS. (10 Marks)",
      "Basketball Practice Scheduling: 3 chances per student. Diagrammatic illustration of completion times. (12 Marks)",
      "Travel Agency Vehicle Allocation: Schedule plan for Groups G1-G4 using Cars A, B, C. (8 Marks)",
      "Real-time OS challenges and Monitor/User mode protection mechanism. (5 Marks)",
      "Pthreads: Thread 1 prints primes, Thread 2 counts words in a file. (5 Marks)",
      "Web Server Hit Counter: Compare Mutex Lock vs Atomic Integer efficiency. (5 Marks)",
      "Working Set Model W(t, delta) calculation. Effective Access Time with page fault rate. (5 Marks)",
      "Two-Level Paging: Calculate bits for second-level index and total virtual pages. (5 Marks)",
      "Para-virtualization explanation with example and Access Matrix description. (10 Marks)",
      "Collatz Conjecture using Pthreads. (6 Marks)",
      "Multithreading Models: Differentiate Many-to-One vs Many-to-Many. (5 Marks)",
      "Banker's Algorithm: 5 processes, 4 resources. Safe state check and request grant. (10 Marks)",
      "Sleeping Barber Problem solution using Semaphores. (10 Marks)",
      "Live Migration of a running guest OS. Conceptualize. (5 Marks)",
      "Remote File Systems failure semantics vs Local File Systems. (5 Marks)",
      "Fork(): Check if numbers are special (divisible by 5 & 7) in child process. (10 Marks)",
      "Advocate Client Scheduling: FCFS vs Priority based on case file order. (10 Marks)",
      "Process Coordination: Printing File (Read -> Copy -> Print) using Semaphores. (10 Marks)",
      "Average Access Time calculation for Write-back vs Write-through cache policies. (10 Marks)",
      "RTOS Security issues in software development lifecycle. (10 Marks)",
      "Embedded OS for Smart Home Appliances. Architecture justification. (10 Marks)",
      "Server Connection Limiting (Max N connections). Semaphore pseudocode. (10 Marks)",
      "Linked File Allocation: Illustrate with diagram. Advantages/Disadvantages. (10 Marks)",
      "LRU Page Faults comparison for Frame size 100 bytes vs 75 bytes. (10 Marks)",
      "Server Consolidation: Discuss suitable virtualization type. (10 Marks)",
      "OS Architecture for Autonomous Vehicles vs Cloud Data Centers. (10 Marks)",
      "Process Hierarchy Tree: P1 -> P2 -> P3. Fork() output prediction. (10 Marks)",
      "Public Distribution System: Two queues (Price based). Round Robin scheduling. (10 Marks)",
      "Banker's Algorithm: TechSoft IT Industry (Analyst, Architect, Tester, Developer resources). (10 Marks)",
      "Database Administrator: Data Access Methods and Storage Structures. (10 Marks)",
      "Concurrent Program 'total' variable bounds. Semaphore solution for determinism. (10 Marks)",
      "Robotic Arm Disk Scheduling: SSTF calculation. Rotational Latency calculation. (10 Marks)",
      "Inventory Management: Locks for stock modification, order processing, starvation prevention. (15 Marks)",
      "Car Parking Allocation: First/Best/Worst Fit algorithms. Calculate fragmentation. (6 Marks)",
      "Design Smart Home Hub Layered OS vs Microkernel. Explain structure and maintenance. (10 Marks)",
      "Analyze Fork code: float a=2.0; fork();. Interpret output and memory storage. (5 Marks)",
      "Handle Zombie Process: PPID 3421 running. How to remove zombie? Write C program for Orphan. (10 Marks)",
      "Student Internet Access: Centre A (Priority CGPA), Centre B (RR 3ms). Calculate Wait Time. (12 Marks)",
      "Multi-core Round Robin Scheduling: 3 cores, q=4. Calculate TAT, CT, WT. (10 Marks)",
      "Drone OS Kernel Model: Design for autonomous delivery drones. Real-time decision making. (10 Marks)",
      "IoT Smart City OS: Design structure (Monolithic/Micro/Layered) for traffic/sensors. (10 Marks)",
      "Hotel Room Service Simulation: Parent creates n child managers. Sleep logic. (10 Marks)",
      "Electric Vehicle OS: Critical vs Non-critical system separation. Fault isolation. (10 Marks)",
      "Traffic Control Hybrid Scheduling: Priority for specific vehicles + RR for others. Gantt chart. (10 Marks)",
      "Multilevel Feedback Queue: Q1(RR q=3), Q2(RR q=6), Q3(FCFS). Aging and Promotion rules. (10 Marks)"
    ]
  },
  {
    subject: "Database Management Systems",
    style: "Highly analytical. Focus covers ER/EER modeling (Banking, Hospital, Vehicle Rental), Relational Mapping, Normalization (up to BCNF/4NF), and detailed Transaction Management (Serializability, Log-based Recovery, 2PL). Indexing (B+ Trees, Hashing) and Distributed DBs (CAP Theorem) are frequently asked.",
    samples: [
      "Compare File Processing Systems vs DBMS for a Pesticide Company. Explain the Three-Schema Architecture. (10 Marks)",
      "Draw an ER diagram for a Smart Health Clinic (Patients, Doctors, Appointments, Tests, Insurance). Handle weak entities and relationships. (10 Marks)",
      "Normalize the relation ORDER_DETAILS (OrderID, CustomerID, ProductID...) up to 3NF. Check for Lossless Join and Dependency Preservation. (15 Marks)",
      "Construct a B+ Tree of order 4 for keys: 32, 14, 56, 73... Show step-by-step insertion. Delete keys 19 and 73 and show the final tree. (15 Marks)",
      "Check if the given Schedule S1 is Conflict Serializable using a Precedence Graph. If not Cascadeless, convert it. (10 Marks)",
      "Apply Timestamp Ordering Protocol to the given schedule of 3 transactions (T1, T2, T3). Analyze the operations. (5 Marks)",
      "Explain CAP Theorem in the context of a distributed social media platform. Which properties are guaranteed during partition? (10 Marks)",
      "Write SQL queries and Relational Algebra for: 'List passengers on Route 201', 'Count buses from Mumbai to Chennai'. (10 Marks)",
      "Illustrate Log-based Recovery using Deferred and Immediate Modification for a schedule with crash scenarios. (10 Marks)",
      "Design an EER diagram for a Vehicle Rental System with superclass Vehicle and subclasses Car, Truck, Motorcycle. Handle overlapping/disjoint constraints. (10 Marks)",
      "Given FDs for Airline Reservation, find the Minimal Cover and identify Candidate Keys. (15 Marks)",
      "Construct an Extendible Hashing structure with bucket size 3 for keys 25, 37, 48... showing directory splits. (15 Marks)",
      "Analyze a deadlock scenario using a Wait-for Graph. Suggest prevention techniques. (10 Marks)",
      "Compare SQL vs NoSQL. When would you choose a Document store over a Relational DB for an e-commerce platform? (10 Marks)",
      "Show the execution of a schedule under Basic 2PL, Strict 2PL, and Rigorous 2PL. Identify lock points. (10 Marks)",
      "You are a DBA for a Client/Project Management DB. Discuss functionalities of DBMS components and User roles. (10 Marks)",
      "Suggest architecture for Driverless Car Management System (DCMS) handling fleet, tracking, and payment. (10 Marks)",
      "Write SQL for StudentInfo/StudentClub tables: Create, Join, Group By, Constraint Violations. (10 Marks)",
      "Construct ER Diagram for Jewellery Store: Customers, Jewels, Orders, Suppliers, Stock. Handle attributes/cardinality. (10 Marks)",
      "Convert University ER Diagram (Student, Course, Instructor, Library) to Relational Schema. (5 Marks)",
      "Grocery Store: Justify File System vs Relational DBMS. Explain Three-Schema Architecture. (10 Marks)",
      "Multi-Speciality Hospital DB: Select Data Model, Justify choices, Explain Data Independence. (10 Marks)",
      "Write SQL: Create tables Department/Professor/Course. Add Constraints (Date, Semester Default, Credits check). (10 Marks)",
      "Map Library Management System ER Diagram to Relational Schema with constraints. (10 Marks)",
      "Find Canonical Cover and Candidate Keys for relation R(A-I) with given FDs. (10 Marks)"
    ]
  },
  {
    subject: "Computer Networks",
    style: "Heavy focus on numericals and network design. Key areas: IP Addressing & Subnetting (VLSM, CIDR design for departments), Routing Algorithms (Dijkstra/Distance Vector dry runs), Error Detection (CRC/Hamming Code calculations), and Delay/Latency analysis. Questions often involve analyzing raw Protocol Headers (IPv4/TCP Hex dumps) and interpreting TCP Congestion Control graphs.",
    samples: [
      "An organization has been allocated the address block 10.20.0.0/16. Design a subnetting scheme using VLSM for 4 departments with 400, 100, 50, and 10 hosts. Determine masks and address ranges. (10 Marks)",
      "Given the IPv4 header in hexadecimal (45 00 00 3c...), decode fields like Total Length, Protocol, Source IP, and determine the payload size. (10 Marks)",
      "Use Dijkstra's algorithm starting from node B to find the shortest path tree and forwarding table. Show all iteration steps. (10 Marks)",
      "A bitstream is transmitted using CRC with generator polynomial x^3+1. Calculate the transmitted frame. If the 3rd bit is flipped, explain how the error is detected. (10 Marks)",
      "Calculate total latency for a frame of size 3 million bits on a link with 5 routers, bandwidth 3Mbps, and specific queuing/processing times. Identify the dominant delay component. (7 Marks)",
      "Analyze the given TCP Congestion Window graph. Identify slow start, congestion avoidance phases, and how many times duplicate ACKs were received. (8 Marks)",
      "TFTP Packet Fragmentation: Payload 3000 bytes, MTU 1500. Calculate fragments, MF flag, Offset, and Efficiency. (10 Marks)",
      "University Subnetting: 172.16.0.0/22 for Admin(256), Acad(256), Student(128), Security(64). Design IP scheme. (10 Marks)",
      "Decentralized Routing: 7 Routers. Compute routing tables after 2 iterations. Link failure count-to-infinity analysis. (10 Marks)",
      "TCP Congestion Control: MSS 2KB, Threshold 32KB. Timeout at 36KB. Analyze cwnd after timeout and 3 Dup ACKs. (10 Marks)",
      "Identify Flow Control (Stop-and-wait, GBN, SR) from frame sequence F1 A1 F2 A2... Calculate efficiency. (10 Marks)",
      "ISP Subnetting: 120.60.4.0/20 for 2500 customers (Engg, Mgmt, Law, Arts). Design subblocks. (10 Marks)",
      "Slotted ALOHA Throughput: N stations, 200 Kbps channel. Max throughput and max stations supported. (10 Marks)",
      "Sliding Window Protocol: Moon Link (1.5 Mbps, 1.25s latency). Calculate min sequence bits for GBN/SR. (10 Marks)",
      "IP Fragmentation: 4020 bytes payload, MTU 1500. Calculate Total Length, MF, Offset for all fragments. (10 Marks)",
      "Fixed-Length Subnetting: 16.0.0.0/8 into 500 subnets. Find mask, range for Subnet 1 and 500. (10 Marks)",
      "Compare Topologies (Mesh, Ring, Bus, Star) for 100 devices. Cable links, ports, fault tolerance. (10 Marks)",
      "Switching Addressing: Role of addressing in Circuit, Datagram, and Virtual Circuit networks. (10 Marks)",
      "CRC Calculation: Data 101110110101, 9-bit polynomial. Detect error if 3rd and 7th bits flip. (10 Marks)",
      "Transport Layer: Choose protocol for Real-time Chat. Explain 3-way handshake and metadata. (10 Marks)",
      "DNS Resolution: Calculate total time with Local, Root, TLD, Authoritative servers. Impact of caching. (10 Marks)"
    ]
  },
  {
    subject: "Computer Architecture and Organization",
    style: "Deep focus on calculation and tracing. Questions require step-by-step execution of algorithms (Booth's, Restoring Division), tracing instruction cycles (Fetch-Decode-Execute) with register contents, and designing memory/control units. High emphasis on quantitative performance analysis (Amdahl's Law, Speedup, CPI) and memory hierarchy design (Cache mapping, Interleaving).",
    samples: [
      "With relevant sketches, explain the stored-program concept as implemented in the IAS computer following the Von Neumann architecture. Contrast this with the Harvard architecture. (10 Marks)",
      "Multiply A = 001011 and B = 011011 using the Booth algorithm. (5 Marks)",
      "A hard disk has 4 heads, each track can store 512 KB of data, 7200 RPM. Calculate transfer rate. Compare SSD vs Magnetic. (10 Marks)",
      "Explain in detail about DMA control with suitable diagrams. Discuss how it improves the overall performance. (10 Marks)",
      "Receiver gets 7-bit Hamming code 1011011 (even parity). Calculate syndrome bits, find error position, and correct data. (5 Marks)",
      "RAID 5 system with disks D0, D1, D2, D3. Stripe data: 1010, 1100, 0011. Calculate parity. If D1 fails, show reconstruction equation. (5 Marks)",
      "Show that a five-stage pipelined architecture achieves saving on execution time vs non-pipelined. Calculate speedup. List hazards. (10 Marks)",
      "Explain Flynn's Classification of parallel hardware. (10 Marks)",
      "Consider a 2-way set-associative cache with 8 blocks. Request sequence: 4, 251, 1, 27, 3, 82... Show cache structure changes, hit/miss ratio for FIFO and LRU. (15 Marks)",
      "Compare Processor P1 (3GHz, CPI 1.8) and P2 (2.5GHz, CPI 1.2) for 10^6 instructions. Calculate execution time and relative speedup. (5 Marks)",
      "Trace execution of instructions (Store R3, (R15); Add R2, R1, R4; Sub R5, R2, R6) on a RISC architecture. Identify register contents. (15 Marks)",
      "Perform Restoring Division for Dividend=13 and Divisor=3 using 4-bit register. Show Accumulator/Quotient at each step. (15 Marks)",
      "Describe initialization of a DMA controller. Explain bus arbitration and compare Burst vs Cycle Stealing modes. (15 Marks)",
      "Identify Flynn's Taxonomy for: Autonomous Vehicle Navigation, Live Weather Prediction, High-Frequency Stock Trading. Justify. (15 Marks)",
      "Implement expression O = (B + M) * (T - S) using 3-address, 2-address, and 1-address formats. (6 Marks)",
      "Analyze a network router's 2-way set associative cache (8 blocks) for a specific packet stream. Calculate hit ratio. (10 Marks)",
      "Propose a RAID configuration for a hospital IT system balancing performance, fault tolerance, and cost. (10 Marks)",
      "Perform Non-Restoring Division for Dividend 21 and Divisor 4. (5 Marks)",
      "Illustrate Multi-bus architecture support for parallel movement of data for LOAD R1, [A]; SUB R3, R1, R2. (10 Marks)",
      "Design a 32K x 16-bit RAM module using 8K x 8-bit chips with interleaving. Show address mapping and decoder logic. (10 Marks)",
      "For address hex 52C, extract tag, set, offset for Direct Mapping and 8-way Set Associative (14-bit address, 2048B cache, 32B block). (10 Marks)",
      "Explain Handshaking mechanisms (source-initiated vs destination-initiated) to overcome unreliable strobe pulses. (5 Marks)",
      "Compute CRC bits for data 10110110 using G(x) = x^4 + x + 1. Demonstrate error detection if 5th bit is corrupted. (10 Marks)",
      "Calculate Amdahl's Law speedup for a cloud gaming platform (Physics, Texture, Lighting components) using 8-core GPU. (10 Marks)",
      "Design a Register File for a processor with 64 registers (32-bit). Calculate storage capacity. (5 Marks)",
      "Convert (85.125)10 to IEEE 754 single-precision. Add (234.45)10 and (122.35)10 in IEEE format. (10 Marks)",
      "Write Assembly Language Program for P = (X - Y + Z) * (A - B) / Q using 0, 1, 2, 3 address formats. (10 Marks)",
      "Analyze Microinstruction trace (PCout, MARin, Read...) and identify the instruction. Develop control sequence for Multipath CU. (10 Marks)",
      "Compare Programmed I/O vs Interrupt-Driven I/O vs Handshaking for a real-time patient monitoring system. (10 Marks)",
      "Identify Hazards in pipeline sequence: LOAD R1, 200(R2); ADD R3, R1, R4; SUB R5, R3, R6; MUL R7, R5, R8. Propose solutions. (10 Marks)",
      "Illustrate operational steps for swapping two numbers at memory 351 and 352 using LDA, MOV, STA instructions. Trace PC, MAR, MBR. (10 Marks)",
      "Design floating point subtraction algorithm for IEEE single-precision. Test with 234.625 - 125.25. (10 Marks)",
      "Calculate average memory access time for a system with Cache (20ns), Main Memory (60ns), Disk (12ms) and Hit ratios 0.9/0.6. (5 Marks)",
      "Design a synchronous bus system (20MHz) for CPU-Peripheral communication. Explain Read/Write sequence and Arbitration. (10 Marks)"
    ]
  },
  {
    subject: "Theory of Computation",
    style: "Rigorous proofs and construction of abstract machines. Focus on converting between models (RE -> NFA -> DFA), minimizing automata, and proving properties using Pumping Lemma. Deep dive into Turing Machine design for functions/languages, PDA construction for CFLs, and Decidability problems (PCP, Halting). CYK algorithm traces are common.",
    samples: [
        "Construct an equivalent Deterministic Finite Automata (DFA) for the NFA with null moves given in Figure 1. (10 Marks)",
        "Using the equivalence method, check whether the two given finite automata M1 & M2 are equal. (10 Marks)",
        "Design a regular expression for strings in {0,1}* having no more than three 0's or number of 1's divisible by two. Design the corresponding NFA. (5 Marks)",
        "Construct a Context Free Grammar for L = {0^i 1^j | i != j} or L = {a^n b^n c^m | m >= 1}. (5 Marks)",
        "Fit the language L2 = {a^p | p is prime} in Chomsky's hierarchy and design an automata to justify. (10 Marks)",
        "Design a DFA for the language accepting binary numbers divisible by 3. Construct the regular expression from it. (10 Marks)",
        "Construct a CFG in Greibach Normal Form (GNF) for the scenario: 'blue shells first, red second, green last; count(blue) = count(red) + count(green)'. (10 Marks)",
        "Validate the string 'aabbee' using the CYK algorithm for the grammar: S->ABC, A->aA|a, B->bB|b, C->cC|c. (10 Marks)",
        "Is the language L = {<M> | L(M) is empty} decidable? Justify. (10 Marks)",
        "Determine if the given Post Correspondence Problem (PCP) instance has a solution: List A=[ab, abb, abb, aaa, ab], List B=[ba, bba, ba, aa, aba]. (10 Marks)",
        "Design a finite automaton for L = {w | w contains odd number of 1's or pattern '020'}. (10 Marks)",
        "Construct an equivalent DFA for the NFA defined by the transition table (q1, a)->q1, (q1, epsilon)->q2... (10 Marks)",
        "Check if the grammar G: ({S, B, C}, {a, b, c}, P, S) is ambiguous. (10 Marks)",
        "If A and B are regular, is the Equal Concatenation EC(A,B) = {xy | x in A, y in B, |x|=|y|} regular? (10 Marks)",
        "Construct an equivalent GNF for the CFG: S->AA|a, A->SS|b. (10 Marks)",
        "Generate a CFG and design a PDA for HTML structure (matching tags). (10 Marks)",
        "Construct a PDA for the language defined by S->aSa|bSb|... (Palindromes). (10 Marks)",
        "Design a Turing Machine to sort strings of 1s and 0s (rearrange 0s to left, 1s to right separated by #). (10 Marks)",
        "Design a Turing Machine to compute f(x,y) = x AND y. (10 Marks)",
        "Let L1 be regular and L2 be context-free. Is L1 - L2 regular? Justify. (10 Marks)",
        "Prove using induction that (xy)^R = y^R x^R. (5 Marks)",
        "Prove that for any CFG in CNF, deriving a string of length n requires exactly 2n-1 steps. (5 Marks)",
        "Define an NFA for strings where the final digit has appeared before. Convert to DFA. (10 Marks)",
        "Design an NFA to validate passwords (uppercase, lowercase, digit, start char, length >= 8). Convert to DFA and minimize. (10 Marks)",
        "Convert the DFA to Regular Expression using state elimination method. (10 Marks)",
        "Prove L = {a^n b^j c^k | k > n > 0} is not regular using Pumping Lemma. (5 Marks)",
        "Check ambiguity for the expression grammar: S->expr, expr->unary|binary|term... (5 Marks)",
        "Use CYK algorithm to parse 'wabaaba' for the grammar with P defined by ... (10 Marks)",
        "Develop a PDA for L = {a^m b^n c^p d^q | m+n = p+q}. (10 Marks)",
        "Construct a Turing Machine for binary addition of two numbers. (10 Marks)",
        "Design a total Turing Machine for L = {c^n b^n a^n | n >= 1}. (10 Marks)",
        "If a collection of languages partitions Sigma* and each is RE, prove each is recursive. (10 Marks)",
        "Describe the language for RE (2* a 2* a U b b)* b*. Give a string in and not in the language. (10 Marks)",
        "Draw NFA for L = {w | w starts with 0 and odd length OR starts with 1 and length <= 5}. Convert to DFA. (10 Marks)",
        "Construct Finite Automata and RE for the 'Bakery' scenario (Bread, Milk, Egg transitions). (10 Marks)",
        "Use CYK to determine if 'bbbaac' is in L(G) for the given CNF grammar. (10 Marks)",
        "Construct CFG in GNF for 'Paneer, Ghee, Tomato' logic (Paneer first, Ghee next, Tomato last; count(Paneer) = count(Ghee) + count(Tomato)). (10 Marks)",
        "Find minimum pumping length for (010)*1. Explain why p-1 is not a pumping length. (10 Marks)",
        "Design PDA for L = {w | w is odd length and contains at least two 0's}. (10 Marks)",
        "Simplify grammar S->aSa | bSb | epsilon. Check ambiguity. (10 Marks)",
        "Design a Turing Machine that doubles the input string (111 -> 111111). (10 Marks)",
        "Show that a language is recognized by a Queue Automaton iff it is Turing Recognizable. (10 Marks)",
        "Construct Automaton and Grammar for L = {a^n b^n c^m} U {a^n b^m c^m}. (10 Marks)",
        "Design DFA for L = {w | n_a(w) mod 3 > n_b(w) mod 3}. (10 Marks)",
        "Write RE for: strings with 'ab', at most one 'aa'/'bb', length divisible by 6, 5th from last is 'b'. (10 Marks)",
        "Compute CFG in CNF for Group Logic (A>B, C=D). (10 Marks)",
        "Design Turing Machine for f(n) = n mod 2 (unary). (10 Marks)",
        "Minimize the DFA given by the transition table (States 1-12). (10 Marks)",
        "Construct PDA for L = {a^n b^m | n <= m <= 3n}. (10 Marks)",
        "Design Turing Machine for L = {a^n b^n c^n} or {w | every a followed by b}. (10 Marks)",
        "Identify Chomsky type for L = {a^i b^j c^k | k > i, j > 2k}. (10 Marks)",
        "Solve the Modified PCP instance given. (10 Marks)",
        "Prove using structural induction: For every tree, nodes = edges + 1. (10 Marks)",
        "Determine FA for L = {w | every 0 in w has a 1 immediately to its right}. (4 Marks)",
        "Minimize the DFA using the minimization algorithm. (10 Marks)",
        "Convert RE (01*0 + 10*1)(0+11)* to epsilon-NFA and DFA. (10 Marks)",
        "Prove L = {a^N b^M | N < M} is not regular using Pumping Lemma. (10 Marks)",
        "Use CYK method for string 110100 on the given CNF grammar. (10 Marks)",
        "Construct CNF for S->pPp|qQq... (10 Marks)",
        "Design PDA for L = {w c w' | w' is 1s complement of w}. (10 Marks)",
        "Trace Turing Machine output for input 1001 (divisible by 3 check). (10 Marks)",
        "Prove: If L is recursive, so is L complement. Universal Language is RE but not Recursive. (10 Marks)",
        "Compute epsilon-closure, strings of length <=3, and convert NFA to DFA. (10 Marks)",
        "Minimize the DFA (States A-I). (10 Marks)",
        "Prove languages are not regular: {a^n b^m | n != m}, Perfect Squares. (10 Marks)",
        "Construct NFA for L1 U L2, L1 intersection L2, L1 - L2. (10 Marks)",
        "Design CFG for RE (0 U (10)* 1)* and derive string. (10 Marks)",
        "Design PDA for 'Colored Balls' scenario (count need not be same, place in bucket). (10 Marks)",
        "Design Turing Machine for Palindromes (reverse of first part). (10 Marks)",
        "Decidability of L = {<M> | M accepts exactly 3 strings}. (5 Marks)",
        "Construct DFA for Access Code system (ends with 000/111, contains 101/010). (10 Marks)",
        "Convert NFA to DFA (transition table provided). (5 Marks)",
        "Describe the language accepted by the DFA diagram (trap state D). (5 Marks)",
        "Construct CFG for L = {a^i b^j c^k | j is even, k is odd}. (5 Marks)",
        "Design Turing Machine for 'Fruit Packing' (Watermelon bottom, Guava, Mango, Chiku). (10 Marks)",
        "Express 'Candy Arrangement' as Context Sensitive Language and design LBA. (10 Marks)",
        "Minimize the ATM Finite Automata states. (10 Marks)",
        "Design machine for L = {a^n b^n c^n}. (10 Marks)",
        "Check Context-Free nature of {0^n 1^n 2^n}. (10 Marks)",
        "PCP Application and solution for given instance. (10 Marks)",
        "RE and FA for University Student Email ID validation. (10 Marks)",
        "Derive SQL query using grammar and construct parse tree. Is SQL grammar regular? (10 Marks)",
        "Check if L = {a^n b^j c^k | k = nj} is context-free. (10 Marks)",
        "Construct DFA for NFA (Fig 1) and check word 'baabbabbb'. (10 Marks)",
        "Design PDA for L = {a^n b^m c^k | n=m or m=k}. (10 Marks)",
        "Construct MPCP solution for Lists A: [a, abb, b], B: [ab, ba]. (10 Marks)",
        "Write grammar for balanced parentheses, identifiers, arithmetic expressions. (10 Marks)",
        "Convert grammar to CNF: S->bA|aB... (10 Marks)",
        "Apply CYK algorithm for boolean query string 'c = 1 || c = 2 && c = 3'. (15 Marks)",
        "Decidability of L = {<M> | L(M) is finite}. (8 Marks)",
        "Design Turing Machine for f(x) = 2x (unary). (7 Marks)",
        "Construct FSM for Fragile X Syndrome pattern (gcg, (cgg|agg)+, ctg). (10 Marks)",
        "Is intersection of two regular languages regular? (5 Marks)",
        "Apply Arden's Theorem to derive RE for the given FA. (10 Marks)",
        "Design PDA for Coupon Machine (Men: n+1, Women: 2n). (10 Marks)",
        "Construct minimized DFA for Automaton M (Fig 3). (10 Marks)",
        "Design Turing Machine for XML structure validation. (10 Marks)",
        "Design Turing Machine for f(x) = x + 2 (unary). (10 Marks)",
        "Fit L = {a^n b^n c^n} in Chomsky hierarchy and design grammar. (10 Marks)",
        "PCP for code repair (Token matching). (10 Marks)",
        "Construct CFG for 'Online Shopping' queries (find [category] [condition]). (10 Marks)",
        "Show derivation for 'find shoes under 1000' and 'find bags watches between 500 and 2000'. (10 Marks)",
        "Check if Gmail password grammar rejects invalid passwords. (10 Marks)",
        "Prove set of suffixes of regular language is regular. (5 Marks)",
        "Design CFG for 'Order Strings' (o i r i [r,r]). Draw phrase tree. (10 Marks)",
        "Design NPDA for Ticket/Receipt code (reverse string). (10 Marks)",
        "Construct Turing Machine for L = {w @ w}. (10 Marks)",
        "Convert CFG to GNF: S->AA|0, A->SS|1. (15 Marks)",
        "Rice's Theorem application for Spam Filter property. (15 Marks)",
        "Construct NFA without epsilon for given table. (5 Marks)",
        "Minimize DFA using equivalence method (States A-G). (5 Marks)",
        "Design DFA for binary strings divisible by 2 and 3. (5 Marks)",
        "Design DFA for n_a(w) >= n_b(w). (5 Marks)",
        "Design NFA for strings ending in 010 with 011 before, or ending in 101 with 100 before. (5 Marks)",
        "NFA for binary strings with length divisible by 2, 3, or 5. (5 Marks)",
        "Show regular languages closed under Shuffle. (6 Marks)",
        "Thompson Construction for (aab)*(a U aba). (4 Marks)",
        "PDA for {w | w is odd length, middle is 0}. Show configurations. (10 Marks)",
        "Prove intersection of CFL and Regular is CFL. Use to show {w in {a,b,c}* | equal a,b,c} not CFL. (10 Marks)",
        "Decide PCP instance: A=(ab, baa, aba), B=(aba, ba, b). (5 Marks)",
        "Show L = {a^n b^n c^n} is not CFL using CYK trace. (10 Marks)",
        "Show L(G) is CFG and emptiness is decidable. (5 Marks)",
        "Closure properties: Recursive vs RE but not Recursive. (5 Marks)",
        "TM for L = {0^n | n is power of 2}. (10 Marks)",
        "DFA for binary numbers with remainder 2 or 3 when divided by 4. (5 Marks)",
        "DFA for (a|b)* a (a|b). (5 Marks)",
        "Derive RE for given automaton. Minimize given DFA. (10 Marks)",
        "RE and NFA for L = {0^i 1^j | i even, j odd}. (10 Marks)",
        "CFG for L = {a^n b^m c^k | n,m,k constraints}. LMD validation. (10 Marks)",
        "Convert to GNF: S->ABC, A->aA|a... (10 Marks)",
        "Verify string 'abcdef' using CYK for given grammar. (10 Marks)",
        "Check regularity of L = {w | n_0(w) mod 3 != n_1(w) mod 3}. (5 Marks)",
        "Check context-free nature of L = {w | n_a(w) / n_b(w) = n_c(w)}. (5 Marks)",
        "DPDA for L = {0^n 1^m 2^k | n odd, m even, k>0}. (10 Marks)",
        "TM for L = {a^n b^n c^n d^n} (alphabetical order). (10 Marks)",
        "Discuss Chomsky hierarchy with examples. (5 Marks)",
        "Define Fibonacci string sequence S(n) and prove L = {S(n)} is not regular. (10 Marks)",
        "Convert VIT Sports Competition problem to formal language, grammar, and automaton. (10 Marks)",
        "CYK Algorithm for w = abba using specific CNF grammar. (10 Marks)",
        "True/False proofs: If L1 U L2 is regular, are L1/L2 regular? (10 Marks)",
        "Design PDA for L = {a^n b^m | n > m+2} and L = {a^n b^2n c^k | n,k >= 1}. (10 Marks)",
        "Design PDA for Magazine Distribution (House 1=5, 2=4, 3=1). (8 Marks)",
        "Is L = {a^n b^m | n != m} regular? (2 Marks)",
        "Construct CFG for L = {w | n_a(w) = n_b(w)}. (5 Marks)",
        "Design PDA for L = {a^n b^m c^p | n = m + p}. (5 Marks)",
        "Convert Grammar G to CNF: S->aSa|bSb|... (10 Marks)",
        "Construct CFG for L = {0^n 1^n 0^m 1^m}. (10 Marks)",
        "Regularity of L = {a^n b^m | n < m, every 'a' followed by 2 'b's}. (5 Marks)",
        "Design automata for L where n_a(w) is divisible by 3. (10 Marks)",
        "Kindergarten Event: Collect red/blue/green/yellow balls in specific order. Regex and Grammar. (8 Marks)",
        "Toffees Collection: Father(Red,Green), Mother(Yellow), Kid(Blue). Grammar construction. (8 Marks)",
        "Text-based Adventure Game grammar to Greibach Normal Form (GNF). (10 Marks)"
    ]
  },
  {
    subject: "Compiler Design",
    style: "Systematic focus on the compilation phases. Key areas: Lexical Analysis (RE to DFA Direct Method), Parsing (LL(1), SLR, CLR Table construction), Syntax Directed Translation (Attributes, Annotated Parse Trees), Intermediate Code Generation (Three Address Code, Backpatching), and Optimization (DAG, Basic Blocks, Flow Graphs).",
    samples: [
      "Explain the compilation process for 'while (a < b) { i++; }' showing output of each phase. (10 Marks)",
      "Construct NFA for the regular expression (0|1)* (00|11) (0|1)*. (10 Marks)",
      "Convert RE (a|b)* abb to DFA using Direct Method. Draw syntax tree, compute firstpos, lastpos, followpos. (10 Marks)",
      "Perform predictive parsing for: expr->expr or term|term... Compute FIRST/FOLLOW and Parsing Table. (10 Marks)",
      "Write semantic rules for R->R|num. Draw annotated parse tree for '132/4/8-2/8-2-1'. (10 Marks)",
      "Generate Three Address Code (Quadruples, Triples, Indirect Triples) for 'if (a<b) x=y+z else x=y-z'. (10 Marks)",
      "Write Grammar and SDT for 3-address code of Boolean expressions. Use backpatching. (10 Marks)",
      "Evaluate effectiveness of Automatic Parallelization and Cache Locality Optimization. (10 Marks)",
      "Show grammar A->Train... is SLR(1). Generate LR(0) collection, Table, Parse string. (15 Marks)",
      "Construct Basic Blocks, CFG, Dominator Tree, Natural Loops for the given 3-address code. (15 Marks)",
      "Construct DAG and optimal target code for the given expression. (15 Marks)",
      "Construct DFA for Regular Expression '1(0|1)*101' using Direct Method. (10 Marks)",
      "Generate canonical collection of LR(0) items and SLR table for Variable Declaration grammar. (10 Marks)",
      "Compute FIRST and FOLLOW for number declaration grammar (scale, precision, base). Construct Predictive Parsing Table. (10 Marks)",
      "Write SDT to compute max/min of numbers based on sign (+/-). Parse '+5, 2, 9, 6'. (10 Marks)",
      "Convert Propositional Logic expressions to 3-address code using grammar. (10 Marks)",
      "Generate Intermediate Code using Backpatching for 'if(year>=2020 && ...)' block. (10 Marks)",
      "Discuss design aspects of parallel machines for parallelizing compilers (Instruction Streams). (10 Marks)",
      "Optimize the given basic blocks. Identify Dominators and Loops. (15 Marks)",
      "Compute Next-Use and Liveness information. Generate Machine Code for 3-register processor. (15 Marks)",
      "Construct Activation Tree and show Control Stack for BinarySearch recursive call. (15 Marks)",
      "Convert RE (a|b)* a b to DFA using Direct Method. (10 Marks)",
      "Construct Non-recursive LL(1) predictive parsing table for grammar S->aBDh... (10 Marks)",
      "Construct Canonical LR (CLR) parsing table for S->CC... Parse string '101&10'. (10 Marks)",
      "Develop Grammar and SDT to convert Prefix to Postfix. Trace for '+ a/*bc-de'. (10 Marks)",
      "Construct Parse Tree and 3-address code for 'while A<C and B>D do...'. (10 Marks)",
      "Find Abstract Syntax Tree, TAC, Quadruple, Triple, Indirect Triple for (a+b)*(c+d)-(a+b+c). (10 Marks)",
      "Categorize Basic Blocks and find CFG for the given code snippet. (10 Marks)",
      "Illustrate DAG for 3-address code block. Find Expression Grammar, Parse Tree, Optimized Code. (10 Marks)",
      "Can evaluation order change during code generation? Explain with example. (10 Marks)",
      "Differentiate Scalar vs Vector processor in compiler design. (10 Marks)",
      "Show grammar 'if expr then stmt...' is ambiguous. Rewrite to remove ambiguity. (10 Marks)",
      "Construct SLR(1) parsing table for S->bAiB... (10 Marks)",
      "Draw table of Semantic Rules for Arithmetic Expression grammar. Build Annotated Parse Tree for 3*5+4. (10 Marks)",
      "Draw Activation Records for 'Pinky(int a, int b)' function call. (10 Marks)",
      "Frame RE for Product ID (P, 5/7+, X/M, F/N). Construct DFA using Direct Method. (10 Marks)",
      "Check if grammar B->BB|B#... is LL(1). (10 Marks)",
      "Construct Grammar and SDT for Hexadecimal to Decimal conversion. Parse 'A35D9'. (10 Marks)",
      "Generate 3-address code using Short-Circuit for nested if-else. (10 Marks)",
      "Apply Backpatching for 'while (a<b) { switch(x) ... }'. (10 Marks)",
      "Outline design of parallel machines supporting parallelizing compilers. (10 Marks)",
      "Generate Canonical LR(1) items and CLR table for S->xAz... Parse 'xp@&%q#z'. (15 Marks)",
      "Apply optimization techniques (Constant Folding, etc.) to Basic Blocks. (15 Marks)",
      "Construct SLR parsing table for S -> L = R | R, L -> * R | id, R -> L. Check SLR property. (10 Marks)",
      "Create annotated parse tree for 'aadbc' using grammar S -> a S b | ... (5 Marks)",
      "Translate (a + b) * (c + d) - (a + b + c) into Quadruples, Triples, Indirect Triples. (10 Marks)",
      "Apply backpatching to generate code for 'while (a < b or a > c) ...'. (10 Marks)",
      "Give SDT to differentiate expressions like x + y * z (variable x, constants). (5 Marks)",
      "Describe Symbol Table lookup process and Type Checker specification. (5 Marks)",
      "Construct Canonical LR parser for S -> CC, C -> cC | d. Parse 'cd#'. (10 Marks)",
      "Dependency graph for expression 8*7-4*9 using given SDT. (8 Marks)",
      "Write Grammar and SDT to find sum of digits. Parse '4876'. (7 Marks)",
      "Convert string %a&b^c#a^%b into 3AC (Quad/Triple/Syntax Tree). (10 Marks)",
      "Construct LALR parser for S -> AA, A -> aA | b. (15 Marks)",
      "Construct SDD with controlled side-effects for declarations 'int a, b, c'. (10 Marks)",
      "Generate DAG for a+a*(b-c)+(b-c)*d. (10 Marks)",
      "Construct CLR(1) parsing table for S -> L=R | R. (8 Marks)",
      "Draw annotated parse tree for 428/4/10-2/5-3-2 using given grammar. (5 Marks)",
      "Generate 3AC, Quadruple, Triple for -(a+b)*(c+d)-(a+b+c). (10 Marks)",
      "Backpatching for Boolean expression (A < B && C < D) || (E < F ...). (10 Marks)",
      "Construct Canonical LR and LALR tables for S -> C C, C -> c C | d. (16 Marks)",
      "Generate 3AC for 'if(number1 > number2 && ...)' using SDT. (5 Marks)"
    ]
  },
  {
    subject: "Digital System Design",
    style: "Focus on combinatorial and sequential logic design. Problems often involve designing circuits for real-world scenarios (Chemical Plants, Dairy Farms, Staircase Switches) using MUX, Decoders, and Gates. Arithmetic circuits (Booth's Algorithm, Comparators) and Verilog coding (Structural, Behavioral, Dataflow) are key components.",
    samples: [
      "Perform multiplication of (-7) x (+3) using Booth's Multiplication algorithm. Find number of additions, subtractions, and shifts. (8 Marks)",
      "Design a circuit for a chemical plant with 4 tanks (High/Low sensors). Alarm if >=2 tanks are High. Use 8:1 Multiplexer. (8 Marks)",
      "Design a control circuit for a Dairy Farm to check milk packet weight (Standard 3kg). Logic for Overweight (>3), Underweight (<3), Perfect (=3). Write Verilog Dataflow code. (10 Marks)",
      "Design a sequential logic circuit to convert Serial Input (Sensor) to Parallel Output (Microcontroller). Write Verilog Behavioral code. (10 Marks)",
      "Analyze the D and JK flip-flop circuit. Formulate a table for the sequence of outputs for the next 5 clock pulses. (10 Marks)",
      "Implement F(A,B,C,D) = Sum(0,1,3,4,8,9,15) using 8:1 MUX with A,C,D as select lines. (4 Marks)",
      "Implement logic for Staircase Switch (2 Bulbs, 4 Switches) using a Decoder. Write Verilog Structural code. (10 Marks)",
      "Write Verilog Behavioral code for a 4-bit Magnitude Comparator. (5 Marks)",
      "Perform multiplication of (-12) x (+8) using Booth's Algorithm. (10 Marks)",
      "Convert a 2-input sequential circuit with forbidden state into a single-input toggling circuit. (4 Marks)",
      "Sketch Q output waveform for D-Latch vs D-Flip Flop for given Clock and Data inputs. (4 Marks)",
      "Encoder generates error detection code using poly x^3+x+1 for message 1011. Determine transmitted codeword. Verify if error in 3rd bit is detected. (10 Marks)",
      "Implement F(A,B,C,D) = Pi(0,1,2,3...) using 8:1 MUX with A,B,C select lines. (5 Marks)",
      "Design a combinational circuit using a Decoder to square a 3-bit number. Write Verilog Dataflow code. (10 Marks)",
      "Implement F = xy + yz + zx using NAND gates only. (5 Marks)",
      "Design a circuit to compare two 3-bit numbers (A, B) and output 1 if A < B. (5 Marks)",
      "Draw logic diagram of 4-bit register with D-FF and 4:1 MUX for operations: No Change, Complement, Clear, Load. (5 Marks)",
      "Obtain Q1 and Q2 waveforms for the given circuit (JK and D Flip Flops) and input trigger signal. (5 Marks)",
      "Implement 4-bit Odd Parity Checker output using 8:1 MUX. (5 Marks)",
      "Compute final value of 4-bit Adder output (S and C_out) for given inputs and Mode M=0/1. Write Verilog Dataflow model. (10 Marks)",
      "Construct logic diagram of 4-bit register with parallel load using D-FF and 2:1 MUX. (5 Marks)",
      "Perform multiplication of 13 and -6 using Booth's Algorithm. (10 Marks)",
      "Identify the digital circuit (MUX/DEMUX combo). Obtain output expression and write Structural modeling. (10 Marks)",
      "Design circuit to generate extra bit for odd parity in 4-bit sensor reading. (5 Marks)",
      "Perform multiplication of -19 and 07 using Booth's Algorithm. (10 Marks)",
      "Identify the circuit (Cascaded Full Adders for 4-bit arithmetic). Write Structural Verilog for V, N, Z flags. (10 Marks)",
      "Analyze T and D flip-flop circuit. Formulate state sequence table for next 5 clocks. (5 Marks)",
      "Simplify Boolean Expression (A+B)(B+C)(A'+C') and Static CMOS for F=(D(A'+BC)+E'). (10 Marks)",
      "Design Missile Launch Logic (2/4 biometric inputs). K-Map, Basic Gates, NAND implementation. (15 Marks)",
      "Verilog Value Sets and Relational Operators explanation. (5 Marks)",
      "Design 5-to-32 Decoder using 3-to-8 Decoders. Verilog Structural code. (15 Marks)",
      "Boolean Reduction WXY'Z and POS form for F(A,B,C,D)=Pi(1,4,6,12,14). (5 Marks)",
      "Full Subtractor Design using Decoder and NAND gates. (10 Marks)",
      "Design 4:2 Priority Encoder. (10 Marks)",
      "K-Map simplification for F=ABCD+AB'C'D'+AB'C+AB. Implement SOP (NAND) and POS (NOR). (15 Marks)",
      "Majority Logic Circuit: Output 1 if more 1s than 0s (4 inputs). Structural Verilog. (10 Marks)",
      "Verilog Bitwise Operations: AND, OR, XOR, Shift. Result Calculation. (6 Marks)",
      "Design Half Subtractor using NOR gates. (5 Marks)",
      "Verilog Behavioral Code for 2:4 Decoder. (5 Marks)"
    ]
  },
  {
    subject: "Design & Analysis of Algorithms",
    style: "Algorithmic design and analysis. Focus on Divide and Conquer, Greedy, Dynamic Programming, Backtracking, and String Matching. Complexities and Recurrence Relations are key. Questions often involve designing algorithms for specific scenarios (Network Security, Games, Scheduling) and proving correctness.",
    samples: [
      "Construct Huffman Tree for elements P-T, 1-3 with given frequencies. Calculate avg bits/symbol. (10 Marks)",
      "Checkerboard Problem: Optimal path for checker from bottom to top row. Maximize cost. Backtracking. (10 Marks)",
      "Circular String: Find lexicographically smallest rotation using Rolling Hash. (10 Marks)",
      "Influence Graph: Detect negative weight cycle using graph algorithm (Bellman-Ford variant). (10 Marks)",
      "Greedy Algorithm: Find longest covering sequence of subsets. Show counterexample where greedy fails. (10 Marks)",
      "Dynamic Programming: Count non-decreasing sorted sub-arrays. (10 Marks)",
      "Knight's Tour: Backtracking algorithm to check reachability from S to G on N*N grid. (10 Marks)",
      "String Matching: Find longest pattern occurring max times in text T. (10 Marks)",
      "Encoded Message: Count valid ways to decode digit string (DP). (10 Marks)",
      "Matrix Chain Multiplication: Compatible sub-chain and optimal parenthesization. (10 Marks)",
      "Rat in a Maze: All paths with Teleporters. (10 Marks)",
      "Pick Letters Game: Max score with constraints (Dimension, Vowels). (10 Marks)",
      "Longest Common Pair Subsequence (LCPS) for two sequences. DP solution. (10 Marks)",
      "N-Integers on Square Board: Backtracking placement with diagonal/row constraints. (10 Marks)",
      "Course Offering: Greedy algorithm to select courses to offer. (10 Marks)",
      "Latin Square: Backtracking to complete partially filled matrix. (10 Marks)",
      "String Matching: First-Half Match and Second-Half Match algorithm. (10 Marks)",
      "Huffman Encoding with variable branching factor 'b'. (10 Marks)",
      "Coin Row Problem: Max value with no adjacent coins (DP). (10 Marks)",
      "LCS of two sequences of matrices. Recurrence and Algorithm. (10 Marks)",
      "Maximum Event Participation (MEP) problem algorithm. (10 Marks)",
      "Activity Selection with Pattern P constraint. (10 Marks)",
      "N-Queens Algorithm analysis (recursion calls, complexity). (10 Marks)",
      "Travelling Salesman Problem (TSP) algorithm and illustration. (10 Marks)",
      "Place N/2 Queens and N/2 Rooks on N*N board. Backtracking. (10 Marks)",
      "Interwoven Strings: Check if S1 and S2 are interwoven in T. (10 Marks)",
      "Robot Navigation: Algorithm and illustration. (10 Marks)",
      "Investment Selection: Pruning exponential search. (10 Marks)",
      "Distinct Substrings Count. (15 Marks)",
      "Job Scheduling: Minimize makespan on 2 processors (Greedy). (10 Marks)",
      "Knapsack Problem using FIFO Branch and Bound. (10 Marks)",
      "Rabin-Karp Algorithm: Spurious hits calculation (Mod 13). (10 Marks)",
      "Boolean Expression Parenthesization for True evaluation (DP). (15 Marks)",
      "Subset Sum Problem: Backtracking algorithm fill-in-the-blanks. (15 Marks)",
      "Partial Rabin-Karp: Find occurrences where at least 2/3rd of P matches. (10 Marks)",
      "Lizards and Trees: Arrange lizards so no two eat each other (N-Queens variant). (10 Marks)"
    ]
  },
  {
    subject: "Software Engineering",
    style: "Theoretical and case-study based. Focus on SDLC models (Agile, Waterfall, Spiral), Requirements Engineering, UML Modeling, Design Patterns, and Testing strategies. Questions often ask to apply a model to a specific scenario (e.g., Banking App, Hospital System).",
    samples: [
      "Compare Agile and Waterfall models for a startup developing a social media app. Which is better and why? (10 Marks)",
      "Draw a Use Case Diagram and Class Diagram for a Library Management System. (10 Marks)",
      "Explain the phases of the Spiral Model. When is it most appropriate to use? (5 Marks)",
      "Define Functional and Non-Functional Requirements. List 3 of each for an E-commerce website. (10 Marks)",
      "Explain the Singleton and Factory design patterns with code examples. (10 Marks)",
      "Differentiate between Black Box and White Box testing. (5 Marks)",
      "Calculate Cyclomatic Complexity for a given code snippet. (5 Marks)",
      "Explain the Scrum framework, including Roles, Events, and Artifacts. (10 Marks)",
      "Discuss the importance of Software Configuration Management. (5 Marks)",
      "What is Refactoring? List three code smells and how to fix them. (10 Marks)",
      "PWD Portal Project: Analyze Agile vs Waterfall Model appropriateness. (10 Marks)",
      "XP Practices for CRM System: Phases, Communication improvement, Diagram. (10 Marks)",
      "Work Breakdown Structure (WBS) for Telecom Network Deployment Software. (10 Marks)",
      "Calculate Function Points, Productivity, Cost for Hospital Management System (Factors given). (10 Marks)",
      "Online Food Delivery App: SRS Template (Functional/Non-Functional), Stakeholder engagement. (10 Marks)",
      "Police Work Tracking System: Process Model selection and Architecture Diagram. (10 Marks)",
      "Agile Roles: Customer, End User, Stakeholder. Communication languages. (8 Marks)",
      "CRM Use Case Estimation: Classify Simple/Moderate/Complex tasks. (8 Marks)",
      "Ootumlia Airlines: Extreme Programming (XP) Phases, Iteration Planning. (12 Marks)",
      "Inventory Management System: Requirement Elicitation Techniques. (10 Marks)",
      "Sprint Planning for Airlines System: Backlog, Kanban vs Scrum. (20 Marks)",
      "Function Point Analysis for Complex Product (FI=58). (8 Marks)",
      "Online Railway Ticket Reservation: Process Model justification. (10 Marks)",
      "Agile Scrum for Internet Banking Application. (10 Marks)",
      "POS System Risk Management: Identify Risks and Mitigation. (10 Marks)",
      "Online Exam System WBS and Project Schedule (Gantt). (10 Marks)",
      "COCOMO Estimation for POS System (10 KLOC). (5 Marks)",
      "Healthcare Information System (HIS): Evolutionary Process Model recommendation. (10 Marks)",
      "Fintech Mobile App: Agile XP Phases and Sprint Plan. (10 Marks)",
      "Smart Public Transport System: Product-based WBS and Project Plan. (10 Marks)",
      "Learning Management System (LMS): Requirement Elicitation Techniques. (10 Marks)"
    ]
  }
];

export function getVITBlueprint(topic: string): string {
  const match = VIT_KNOWLEDGE_BASE.find(p => 
    topic.toLowerCase().includes(p.subject.toLowerCase()) || 
    p.subject.toLowerCase().includes(topic.toLowerCase())
  );
  
  if (match) {
    return `HISTORICAL PATTERN FOR ${match.subject}:
    Style: ${match.style}
    Reference Questions:
    ${match.samples.join('\n')}
    `;
  }
  
  return `VIT GENERAL STYLE: Descriptive questions only. Mix of conceptual (2 marks) and application (5-10 marks). No MCQs. Focus on diagrams and step-by-step logic.`;
}
